### ISSUE TITLE
Add sonos-controller to Maven Central

### ISSUE THREAD

**Issue by vmichalak** [vmichalak/sonos-controller#10]
I think it's time to release it publicly.

**Comment by KilianB** [comment]
Bump. I really appreciate if this project gets added to maven central!

**Comment by vmichalak** [comment]
I never add a library to maven central. If anyone know how to do it (from gradle) i take the method :)

**Comment by KilianB** [comment]
http://nemerosa.ghost.io/2015/07/01/publishing-to-the-maven-central-using-gradle/

**Comment by edukun** [comment]
Any update?

**Comment by KilianB** [comment]
@edukun  here is my fork which is available via maven and also adds upnp event support.

https://github.com/KilianB/Java-Sonos-Controller

**Comment by edukun** [comment]
Thank you!! that’s what I needed :)
