### ISSUE TITLE
Stream music directly to device

### ISSUE THREAD

**Issue by KilianB** [vmichalak/sonos-controller#27]
It would be great if we could directly stream music to the speaker. I currently do this by hosting a web server, pushing the file to a folder available on the network and supplying the correct URI to the speaker. This is a bit inconvenient and we should also be able to stream directly from our program to the speaker. Imitating a radio station by UDP or HTML streaming which can then be played back.

**Comment by vmichalak** [comment]
I think it's not the role of Sonos-Controller. Perhaps another lib could do this job on top of sonos-controller.
