### ISSUE TITLE
Sonos UPnP Error 701 (Invalid transition)

### ISSUE THREAD

**Issue by Yosifz8** [vmichalak/sonos-controller#35]
I'm trying to play mp4 file with Sonos-Sontroller:

```
List<SonosDevice> devices = SonosDiscovery.discover();
SonosDevice device = devices.get(0);
String test = "http://213.8.5.155/videoplayback2.mp4";
device.clip(test,"player");
```
With that code is playing the file perfectly.

When i try to open HTTP server on the phone and use the same code with:
String test = "http://192.168.0.103:4020/get-video/test.mp4";

I always get this error:
`Sonos.exception.UPnPSonosControllerException: UPnP Error 701 (Invalid transition) received from 192.168.0.102`

This server is local HTTP server open on the application when i tried to access it from my pc he plays the song perfectly.

**Comment by vmichalak** [comment]
Hi Yosifz8,
Sonos player cannot play video file. It could work with mp3 files ;).

**Comment by Yosifz8** [comment]
Hi Valentin 
It's playing the first file

**Comment by Yosifz8** [comment]
Hi Valentin

It's playing the first URL without any problem.
I even tried to play :`http://192.168.0.103:4020/get-video/test.mp3` and it's not connected to the server and keep giving me the:
`UPnPSonosControllerException: UPnP Error 701 (Invalid transition) received from 192.168.0.102` Error.

Any idea what is 701 error?

**Comment by vmichalak** [comment]
Your endpoint is available in your network ? Perhaps a network issue
